### ISSUE TITLE
Mssing information behavior

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinx-bazel#11]
It shall be configurable, if the documentation generation stops, if needed information is missing or if it shall just print a warning

**Comment by danwos** [comment]
This requirement is really generic. 
Normally, when it stops, this means there are huge problems and sphinx-bazel or sphinx itself can not go. In this situations there is nothing we can do to force the tool to not stop.

But I do not know any case yet, where sphinx-bazel kills the build.
If there is one, we need to fix it.

However, to really cancel if there are "minor" problems you can use the "-W" option of sphinx, which treats every Warning as Error (but really every warning, not only from sphinx-bazel.)
We may only have to check, if really all sphinx-bazel problems throw a correct sphinx-warning instead of printing log message only.

But a first fast check shows that all problems throws a sphinx-warning.

So I would go with the "-W" option of sphinx.

**Comment by apekter** [comment]
Let's use real examples as the basis of the clarification. 
In a case there is no workspace(name = "project") statement in the WORKSPACE file the sphinx-bazel will fail to generate the documentation. The mentioned statement is not mandatory in the bazel WORKSPACE file therefore it makes no much sense that the documentation build fails in this case. 
One option for this specific case could be to take the root of project as a workspace name but that is up for discussion.

**Comment by danwos** [comment]
Thanks for feedback.
I think this behavior got solved by #5.

And yes, that's one of the cases where we need to fix the code, as it should no crash.
However a crash will always kill the build, as it is an unwanted behavior.
No way to go on with the build in such cases.
But all of these cases are bugs, so we need to fix them, if we know them :)
